//Api to call -> http://itunes.apple.com/search?term=jack&limit=4

// const data = [
//     {
//       "wrapperType": "track",
//       "kind": "feature-movie",
//       "collectionId": 1066900798,
//       "trackId": 978943481,
//       "artistName": "George Lucas",
//       "collectionName": "星際大戰6部曲",
//       "trackName": "Star Wars: A New Hope",
//       "collectionCensoredName": "星際大戰6部曲",
//       "trackCensoredName": "Star Wars: A New Hope",
//       "collectionArtistId": 410641764,
//       "collectionArtistViewUrl": "https://itunes.apple.com/us/artist/buena-vista-home-entertainment-inc/410641764?uo=4",
//       "collectionViewUrl": "https://itunes.apple.com/us/movie/star-wars-a-new-hope/id978943481?uo=4",
//       "trackViewUrl": "https://itunes.apple.com/us/movie/star-wars-a-new-hope/id978943481?uo=4",
//       "previewUrl": "http://video.itunes.apple.com/apple-assets-us-std-000001/Video122/v4/0d/37/b8/0d37b859-55b4-2ed3-02d2-e7a7ae8359c6/mzvf_842097924938904897.640x362.h264lc.U.p.m4v",
//       "artworkUrl30": "https://is2-ssl.mzstatic.com/image/thumb/Video6/v4/61/16/ce/6116cec2-d2e8-de26-f80d-38a1685d04b8/source/30x30bb.jpg",
//       "artworkUrl60": "https://is2-ssl.mzstatic.com/image/thumb/Video6/v4/61/16/ce/6116cec2-d2e8-de26-f80d-38a1685d04b8/source/60x60bb.jpg",
//       "artworkUrl100": "https://is2-ssl.mzstatic.com/image/thumb/Video6/v4/61/16/ce/6116cec2-d2e8-de26-f80d-38a1685d04b8/source/100x100bb.jpg",
//       "collectionPrice": 19.99,
//       "trackPrice": 19.99,
//       "collectionHdPrice": 19.99,
//       "trackHdPrice": 19.99,
//       "releaseDate": "1977-05-25T07:00:00Z",
//       "collectionExplicitness": "notExplicit",
//       "trackExplicitness": "notExplicit",
//       "discCount": 1,
//       "discNumber": 1,
//       "trackCount": 6,
//       "trackNumber": 1,
//       "trackTimeMillis": 7490195,
//       "country": "USA",
//       "currency": "USD",
//       "primaryGenreName": "Action & Adventure",
//       "contentAdvisoryRating": "PG",
//       "longDescription": "Luke Skywalker begins a journey that will change the galaxy in Star Wars: Episode IV -  A New Hope. Nineteen years after the formation of the Empire, Luke is thrust into the struggle of the Rebel Alliance when he meets Obi-Wan Kenobi, who has lived for years in seclusion on the desert planet of Tatooine. Obi-Wan begins Luke’s Jedi training as Luke joins him on a daring mission to rescue the beautiful Rebel leader Princess Leia from the clutches of Darth Vader and the evil Empire.",
//       "hasITunesExtras": true
//     },
//     {
//       "wrapperType": "track",
//       "kind": "feature-movie",
//       "collectionId": 1066900798,
//       "trackId": 975101586,
//       "artistName": "George Lucas",
//       "collectionName": "星際大戰6部曲",
//       "trackName": "Star Wars: Attack of the Clones",
//       "collectionCensoredName": "星際大戰6部曲",
//       "trackCensoredName": "Star Wars: Attack of the Clones",
//       "collectionArtistId": 410641764,
//       "collectionArtistViewUrl": "https://itunes.apple.com/us/artist/buena-vista-home-entertainment-inc/410641764?uo=4",
//       "collectionViewUrl": "https://itunes.apple.com/us/movie/star-wars-attack-of-the-clones/id975101586?uo=4",
//       "trackViewUrl": "https://itunes.apple.com/us/movie/star-wars-attack-of-the-clones/id975101586?uo=4",
//       "previewUrl": "http://video.itunes.apple.com/apple-assets-us-std-000001/Video122/v4/f3/2d/46/f32d46a1-eca2-b74a-808c-ebcdba703cef/mzvf_1368034946158690604.640x366.h264lc.U.p.m4v",
//       "artworkUrl30": "https://is2-ssl.mzstatic.com/image/thumb/Video62/v4/59/3f/c9/593fc9e8-b453-4f48-cf43-70c013a70fec/source/30x30bb.jpg",
//       "artworkUrl60": "https://is2-ssl.mzstatic.com/image/thumb/Video62/v4/59/3f/c9/593fc9e8-b453-4f48-cf43-70c013a70fec/source/60x60bb.jpg",
//       "artworkUrl100": "https://is2-ssl.mzstatic.com/image/thumb/Video62/v4/59/3f/c9/593fc9e8-b453-4f48-cf43-70c013a70fec/source/100x100bb.jpg",
//       "collectionPrice": 19.99,
//       "trackPrice": 19.99,
//       "collectionHdPrice": 19.99,
//       "trackHdPrice": 19.99,
//       "releaseDate": "2002-05-16T07:00:00Z",
//       "collectionExplicitness": "notExplicit",
//       "trackExplicitness": "notExplicit",
//       "discCount": 1,
//       "discNumber": 1,
//       "trackCount": 6,
//       "trackNumber": 3,
//       "trackTimeMillis": 8537983,
//       "country": "USA",
//       "currency": "USD",
//       "primaryGenreName": "Action & Adventure",
//       "contentAdvisoryRating": "PG",
//       "shortDescription": "For the first time ever on digital, watch the seeds of Anakin Skywalker's transformation take root",
//       "longDescription": "Watch the seeds of Anakin Skywalker's transformation take root in Star Wars: Episode II - Attack of the Clones. Ten years after the invasion of Naboo, the galaxy is on the brink of civil war. Under the leadership of a renegade Jedi named Count Dooku, thousands of solar systems threaten to break away from the Galactic Republic. When an assassination attempt is made on Senator Padmé Amidala, the former Queen of Naboo, twenty-year-old Jedi apprentice Anakin Skywalker is assigned to protect her. In the course of his mission, Anakin discovers his love for Padmé as well as his own darker side. Soon, Anakin, Padmé, and Obi-Wan Kenobi are drawn into the heart of the Separatist movement and the beginning of the Clone Wars.",
//       "hasITunesExtras": true
//     },
//     {
//       "wrapperType": "track",
//       "kind": "feature-movie",
//       "collectionId": 1365781403,
//       "trackId": 1315255745,
//       "artistName": "Jake Kasdan",
//       "collectionName": "Jumanji : Bienvenue dans la jungle + Jumanji",
//       "trackName": "Jumanji: Welcome to the Jungle",
//       "collectionCensoredName": "Jumanji : Bienvenue dans la jungle + Jumanji",
//       "trackCensoredName": "Jumanji: Welcome to the Jungle",
//       "collectionArtistId": 345346702,
//       "collectionArtistViewUrl": "https://itunes.apple.com/us/artist/sony-pictures-entertainment/345346702?uo=4",
//       "collectionViewUrl": "https://itunes.apple.com/us/movie/jumanji-welcome-to-the-jungle/id1315255745?uo=4",
//       "trackViewUrl": "https://itunes.apple.com/us/movie/jumanji-welcome-to-the-jungle/id1315255745?uo=4",
//       "previewUrl": "http://video.itunes.apple.com/apple-assets-us-std-000001/Video118/v4/42/b9/a0/42b9a0b1-60e4-86c0-36b3-915522d45765/mzvf_172183937853883111.640x354.h264lc.U.p.m4v",
//       "artworkUrl30": "https://is5-ssl.mzstatic.com/image/thumb/Video128/v4/1b/de/09/1bde0997-f4d7-740e-efbb-83bacc7c88d5/source/30x30bb.jpg",
//       "artworkUrl60": "https://is5-ssl.mzstatic.com/image/thumb/Video128/v4/1b/de/09/1bde0997-f4d7-740e-efbb-83bacc7c88d5/source/60x60bb.jpg",
//       "artworkUrl100": "https://is5-ssl.mzstatic.com/image/thumb/Video128/v4/1b/de/09/1bde0997-f4d7-740e-efbb-83bacc7c88d5/source/100x100bb.jpg",
//       "collectionPrice": 14.99,
//       "trackPrice": 14.99,
//       "trackRentalPrice": 5.99,
//       "collectionHdPrice": 19.99,
//       "trackHdPrice": 19.99,
//       "trackHdRentalPrice": 5.99,
//       "releaseDate": "2017-12-04T08:00:00Z",
//       "collectionExplicitness": "notExplicit",
//       "trackExplicitness": "notExplicit",
//       "discCount": 1,
//       "discNumber": 1,
//       "trackCount": 2,
//       "trackNumber": 1,
//       "trackTimeMillis": 7141792,
//       "country": "USA",
//       "currency": "USD",
//       "primaryGenreName": "Action & Adventure",
//       "contentAdvisoryRating": "PG-13",
//       "shortDescription": "Four teenagers in detention discover an old video console with a game they’ve never heard of. When",
//       "longDescription": "Four teenagers in detention discover an old video console with a game they’ve never heard of. When they decide to play, they are immediately sucked into the jungle world of Jumanji in the bodies of their avatars (Dwayne Johnson, Jack Black, Kevin Hart, and Karen Gillan). They’ll have to complete the adventure of their lives filled with fun, thrills and danger or be stuck in the game forever!",
//       "hasITunesExtras": true
//     },
//     {
//       "wrapperType": "track",
//       "kind": "feature-movie",
//       "trackId": 1063466898,
//       "artistName": "J.J. Abrams",
//       "trackName": "Star Wars: The Force Awakens",
//       "trackCensoredName": "Star Wars: The Force Awakens",
//       "trackViewUrl": "https://itunes.apple.com/us/movie/star-wars-the-force-awakens/id1063466898?uo=4",
//       "previewUrl": "http://video.itunes.apple.com/apple-assets-us-std-000001/Video82/v4/a3/ef/25/a3ef253a-208e-3cbc-cbf0-bc444dae2f8d/mzvf_6313901593442783545.640x354.h264lc.U.p.m4v",
//       "artworkUrl30": "https://is2-ssl.mzstatic.com/image/thumb/Video69/v4/c2/55/37/c25537af-f191-ef3a-e23e-117621a98da2/source/30x30bb.jpg",
//       "artworkUrl60": "https://is2-ssl.mzstatic.com/image/thumb/Video69/v4/c2/55/37/c25537af-f191-ef3a-e23e-117621a98da2/source/60x60bb.jpg",
//       "artworkUrl100": "https://is2-ssl.mzstatic.com/image/thumb/Video69/v4/c2/55/37/c25537af-f191-ef3a-e23e-117621a98da2/source/100x100bb.jpg",
//       "collectionPrice": 14.99,
//       "trackPrice": 14.99,
//       "trackRentalPrice": 3.99,
//       "collectionHdPrice": 19.99,
//       "trackHdPrice": 19.99,
//       "trackHdRentalPrice": 4.99,
//       "releaseDate": "2015-12-18T08:00:00Z",
//       "collectionExplicitness": "notExplicit",
//       "trackExplicitness": "notExplicit",
//       "trackTimeMillis": 8302135,
//       "country": "USA",
//       "currency": "USD",
//       "primaryGenreName": "Action & Adventure",
//       "contentAdvisoryRating": "PG-13",
//       "shortDescription": "Lucasfilm and visionary director J.J. Abrams join forces to take you back again to a galaxy far, far",
//       "longDescription": "Visionary director J.J. Abrams brings to life the motion picture event of a generation. As Kylo Ren and the sinister First Order rise from the ashes of the Empire, Luke Skywalker is missing when the galaxy needs him most. It's up to Rey, a desert scavenger, and Finn, a defecting stormtrooper, to join forces with Han Solo and Chewbacca in a desperate search for the one hope of restoring peace to the galaxy.",
//       "hasITunesExtras": true
//     }
//   ];

import axios from 'axios';

const _searchTrack = (requestObj) => {
    return axios.get("http://itunes.apple.com/search", {
        params: {
            term: requestObj.term,
            limit: requestObj.limit
        }
    }).then(response =>{
        return response.data.results;
    }).catch(err => {
        console.log(err);
    })
    //return Promise.resolve(data);
}

export default {
    search: _searchTrack
}